import { NavLink, Route, Routes } from 'react-router-dom'
import { brandData } from './content'

const layout = 'max-w-6xl mx-auto px-4 md:px-8'
const card = 'rounded-3xl bg-white/70 backdrop-blur border border-white/80 shadow-glow'

const qr = <div className="h-40 w-40 border-2 border-dashed border-blueGray/50 rounded-2xl flex items-center justify-center text-center text-sm text-blueGray p-3">二维码占位｜后期替换<br/>扫码联系｜加入悦见</div>

function Nav(){return <header className="sticky top-0 z-20 bg-cream/90 backdrop-blur border-b border-fogBlue/30"><nav className={`${layout} py-3 flex flex-wrap gap-3`}>{brandData.nav.map(([n,p])=><NavLink key={p} to={p} className={({isActive})=>`px-3 py-1.5 rounded-full text-sm ${isActive?'bg-blueGray text-white':'bg-white/70 text-blueGray'}`}>{n}</NavLink>)}</nav></header>}

function Home(){return <main className={`${layout} py-10 space-y-8 animate-fadeUp`}><section className={`${card} p-8 text-center bg-gradient-to-br from-white to-mist`}><p className="text-blueGray">女性AI知识付费社群</p><h1 className="text-6xl mt-3 font-serif">悦见</h1><h2 className="text-2xl mt-2 text-blueGray">女性AI成长社群</h2><p className="mt-5 text-xl">让每个普通女性，轻松靠近AI</p><p className="mt-2 text-blueGray">温柔看见AI，也看见自己的新可能</p><div className="mt-6 flex gap-4 justify-center"><button className="px-6 py-2 rounded-full bg-blueGray text-white">了解社群</button><button className="px-6 py-2 rounded-full bg-white border border-blueGray text-blueGray">立即加入</button></div></section><section className="grid md:grid-cols-2 gap-4">{['AI学习：从零理解AI，学会真正能用起来的工具','内容创作：用AI辅助写作、设计、图片、视频和个人表达','效率提升：把重复劳动交给AI，把时间留给更重要的事','副业探索：寻找适合自己的内容、副业与个人品牌方向','同频链接：遇见同样想成长、想改变、想向前的人'].map(i=><article key={i} className={`${card} p-5 hover:-translate-y-1 transition`}>{i}</article>)}</section><section className={`${card} p-6 flex flex-col md:flex-row gap-6 items-center justify-between`}><div><p>世界在加速，但你不需要一个人奔跑</p><p className="mt-1">现在入局，重塑自我 · 创始招募中</p><p className="mt-2 text-softGold">与未来的自己相遇 · {brandData.slogan}</p></div>{qr}</section></main>}

function Brand(){return <main className={`${layout} py-10`}><section className={`${card} p-8 space-y-4 animate-fadeUp`}><h1 className="text-3xl">悦见｜女性AI成长社群</h1><h2 className="text-xl text-blueGray">让每个普通女性，轻松靠近AI</h2><p>悦见，是一个面向女性的AI成长社群。我们帮助成员从零认识AI，学习真正能落地的AI工具和方法，提升表达力、内容创作力、效率管理能力，并在职业发展、副业探索和个人品牌成长中，看见新的方向，也看见更好的自己。</p><p><b>品牌主张：</b>温柔看见AI，也看见自己的新可能。</p><p><b>品牌口号：</b>{brandData.slogan}</p><p><b>关键词：</b>AI学习｜内容创作｜效率提升｜副业探索｜同频链接</p><p><b>价值观：</b>化焦虑为序曲，聚微光以破局；不困于心，不役于物；行无界，心无惧；向阳生长。</p></section></main>}

const posterBase='w-full max-w-[360px] aspect-[9/16] p-6 '+card+' bg-gradient-to-b from-white to-mist flex flex-col justify-between'
function Posters(){return <main className={`${layout} py-10`}><div className="grid lg:grid-cols-3 gap-6 justify-items-center"> <section className={posterBase}><div><h2 className="text-5xl">悦见</h2><p className="mt-2">女性AI成长社群</p><p className="mt-4">让每个普通女性，轻松靠近AI</p><p className="mt-2 text-blueGray">温柔看见AI，也看见自己的新可能</p><p className="mt-4 text-sm">AI学习｜内容创作｜效率提升｜副业探索｜同频链接</p></div><div><p className="text-softGold">创始招募中</p><p className="text-xs mt-1">与未来的自己相遇 SEE AI · SEE A BETTER YOU</p></div></section><section className={posterBase}><div><h2 className="text-3xl leading-tight">从困顿焦虑<br/>到万众瞩目</h2><p className="mt-3 text-sm text-blueGray">AI时代，女性自我重塑的成长指南</p><div className="mt-4 text-sm space-y-2"><p><b>突破物理边界：</b>一部手机，一台电脑，在家也能高效产出，打造个人品牌</p><p><b>消解成长焦虑：</b>学会AI实用技能，把创作力变成影响力，也变成收入力</p><p><b>同频高质量圈子：</b>拒绝焦虑贩卖，只有真实经验与陪伴，一起成长，一起向前</p></div></div><p className="text-sm">世界在加速，但你不需要一个人奔跑<br/>现在入局，重塑自我</p></section><section className={posterBase}><div><h2 className="text-3xl">悦见｜价格与席位</h2><p className="mt-2 text-sm text-blueGray">越早加入，越早以更轻的成本开启AI成长之路</p><ul className="mt-4 space-y-2 text-sm">{['01 创始期 第1—10人 ¥399','02 早鸟期 第11—30人 ¥499','03 成长期 第31—60人 ¥599','04 跃升期 第61—99人 ¥699','05 固定价 100人起 ¥899'].map(i=><li key={i} className="p-2 rounded-xl bg-white/80">{i}</li>)}</ul></div><p className="text-xs">名额递增，价格递进。在更早的阶段加入，享受更友好的人群价格。和一群正在成长的女性一起，温柔靠近AI，也温柔靠近更好的自己。</p></section></div></main>}

function Long(){return <main className={`${layout} py-10`}><section className={`mx-auto max-w-[420px] min-h-[1600px] ${card} p-6 bg-gradient-to-b from-white via-mist to-cream animate-fadeUp`}><h1 className="text-3xl">社群介绍长图</h1><p className="mt-5">这个社群陪你一起：从零开始认识AI，把成长变成可持续的日常实践。</p><p className="mt-4"><b>适合谁加入：</b>AI小白、内容创作者、职场女性、宝妈与自由职业者、想升级自我的成长型女性。</p><p className="mt-4"><b>你将获得：</b>AI学习、内容创作、效率提升、副业探索、同频链接。</p><p className="mt-4"><b>社群形式：</b>主题分享、共学实践、工具教学、交流答疑。</p><blockquote className="mt-8 border-l-4 border-softGold pl-4 text-lg">你不是跟不上时代，你只是需要一个温柔开始的地方。</blockquote><div className="mt-10 p-4 rounded-2xl bg-white/80"><p>世界在加速，但你不需要一个人奔跑。</p><p className="mt-1">与未来的自己相遇 · SEE AI · SEE A BETTER YOU</p></div></section></main>}

function Welcome(){return <main className="min-h-[calc(100vh-64px)] flex items-center justify-center p-4"><section className={`w-full max-w-[390px] min-h-[740px] ${card} p-6 bg-gradient-to-b from-white to-mist relative overflow-hidden`}><div className="absolute -top-8 -right-8 h-32 w-32 rounded-full bg-fogBlue/40 blur-2xl"/><h1 className="mt-10 text-center text-3xl animate-fadeUp">欢迎来到<br/><span className="text-5xl">悦见</span></h1><p className="text-center mt-3">女性AI成长社群</p><p className="text-center mt-4 text-blueGray">你好，很高兴在这里遇见你。愿你温柔靠近AI，也靠近更好的自己。</p><p className="text-center mt-4">让每个普通女性，轻松靠近AI</p><div className="grid grid-cols-2 gap-3 mt-8">{['AI学习','内容创作','效率提升','同频链接'].map(i=><div key={i} className="rounded-xl bg-white/80 p-3 text-center animate-floatSlow">{i}</div>)}</div><div className="mt-8 flex gap-3"><button className="flex-1 py-2 rounded-full bg-blueGray text-white">了解社群</button><button className="flex-1 py-2 rounded-full border border-blueGray text-blueGray">立即加入</button></div><p className="text-center text-sm mt-6 text-blueGray">温柔看见AI，也看见自己的新可能</p></section></main>}

export default function App(){return <div className="min-h-screen bg-gradient-to-b from-cream to-mist text-slate-700"><Nav/><Routes><Route path="/" element={<Home/>}/><Route path="/brand" element={<Brand/>}/><Route path="/posters" element={<Posters/>}/><Route path="/long-intro" element={<Long/>}/><Route path="/welcome" element={<Welcome/>}/></Routes></div>}
